DROP TABLE USERS 			IF EXISTS;
DROP TABLE ROLES 			IF EXISTS;
DROP TABLE PERMISSIONS		IF EXISTS;
DROP TABLE USER_ROLES		IF EXISTS;
DROP TABLE ROLE_PERMISSIONS	IF EXISTS;


CREATE TABLE USERS(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    ENABLED BOOLEAN,
    PASSWORD VARCHAR(150) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL
);

CREATE INDEX INDEX_USERNAME ON USERS(USERNAME);

CREATE TABLE ROLES(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    ROLENAME VARCHAR(50) NOT NULL
);

CREATE TABLE PERMISSIONS(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    PERMISSIONNAME VARCHAR(50) NOT NULL
);

CREATE TABLE USER_ROLES(
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);

CREATE TABLE ROLE_PERMISSIONS(
    PERMISSION_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);

CREATE TABLE PRODUCTS(
	ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
	VERSION BIGINT,
	SIZE VARCHAR(50) NOT NULL,
	AVAILABLE BOOLEAN NOT NULL,
    PRICE DECIMAL(7, 2) NOT NULL,
    PRODUCTNAME VARCHAR(50) NOT NULL,
    PRODUCTTYPE_ID BIGINT	
);

CREATE TABLE PRODUCTTYPES(
	ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
	VERSION BIGINT,
    PRODUCTTYPENAME VARCHAR(50) NOT NULL
);

CREATE TABLE ORDERPOSITIONS(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    COMMENT VARCHAR(255),
    CREATEDDATE BINARY(255),
    REGISTERED BOOLEAN NOT NULL,
    DONE BOOLEAN NOT NULL,
    MODIFIEDDATE BINARY(255),
    PROVIDED BOOLEAN NOT NULL,
    PRODUCT_ID BIGINT,
    TABLE_ID BIGINT,
    USER_ID BIGINT
);

CREATE TABLE TABLESCUSTOMER(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    TABLENUMBER INTEGER NOT NULL
);




             