DROP TABLE USERS 			IF EXISTS;
DROP TABLE ROLES 			IF EXISTS;
DROP TABLE PERMISSIONS		IF EXISTS;
DROP TABLE USER_ROLES		IF EXISTS;
DROP TABLE ROLE_PERMISSIONS	IF EXISTS;


CREATE TABLE USERS(
    ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
    VERSION INTEGER,
    ENABLED BOOLEAN,
    PASSWORD VARCHAR(150) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL
);

CREATE INDEX INDEX_USERNAME ON USERS(USERNAME);

CREATE TABLE ROLES(
    ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
    VERSION INTEGER,
    ROLENAME VARCHAR(50) NOT NULL
);

CREATE TABLE PERMISSIONS(
    ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
    VERSION INTEGER,
    PERMISSIONNAME VARCHAR(50) NOT NULL
);

CREATE TABLE USER_ROLES(
    ROLE_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL
);

CREATE TABLE ROLE_PERMISSIONS(
    PERMISSION_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL
);

CREATE TABLE PRODUCTS(
	ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	VERSION BIGINT,
	SIZE VARCHAR(50) NOT NULL,
	AVAILABLE BOOLEAN NOT NULL,
    PRICE DECIMAL(7, 2) NOT NULL,
    PRODUCTNAME VARCHAR(50) NOT NULL,
    PRODUCTTYPE_ID BIGINT	
);

CREATE TABLE PRODUCTTYPES(
	ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	VERSION BIGINT,
    PRODUCTTYPENAME VARCHAR(50) NOT NULL
);


             