INSERT INTO USERS VALUES (1,1,TRUE,'$2a$10$WVPq/GcSLNcKECb.wIfGeuFD0etGZpkgh6cgxdzmdzlBGdgp7Jzh2','chris');
INSERT INTO USERS VALUES (2,1,FALSE,'$2a$10$WVPq/GcSLNcKECb.wIfGeuFD0etGZpkgh6cgxdzmdzlBGdgp7Jzh2','Christian');

	
INSERT INTO USER_ROLES VALUES (1,1);
INSERT INTO USER_ROLES VALUES (1,2);

INSERT INTO ROLES VALUES (1,1,'Manager');
INSERT INTO ROLES VALUES (2,1,'Waiter');
INSERT INTO ROLES VALUES (3,1,'Cook');
INSERT INTO ROLES VALUES (4,1,'Barkeeper');

INSERT INTO ROLE_PERMISSIONS VALUES (
	1,
	1
);

INSERT INTO PERMISSIONS VALUES (
	1,
	1,
	'DISABLE'
);

INSERT INTO PRODUCTTYPES VALUES (1,1,'Speise');
INSERT INTO PRODUCTTYPES VALUES (2,1,'Getränke');


