INSERT INTO USERS VALUES (1,1,TRUE,'$2a$10$d.qwe.e8ix11Flhr.BymZ.yQ7jtrYVDukyIPF95CVjun9zk.8ypW.','Manager');
INSERT INTO USERS VALUES (2,1,TRUE,'$2a$10$WEFoWWuM1vLx5jy3N4dYve7QyX6yxz1Q0RaMQ.adobbEdJ9CD3w2y','Waiter');
INSERT INTO USERS VALUES (3,1,TRUE,'$2a$10$EqO6IkePwKYEDXEV31E6vOMPRVleBqpeRZS5H1hxXg1/hg3oL/4uO','Cook');
INSERT INTO USERS VALUES (4,1,TRUE,'$2a$10$B99CwzvY0boqw/JVBOpGvO1fGOoEZaruLC/cFz4VA9fs1GXvTSIUa','Barkeeper');

	
INSERT INTO USER_ROLES VALUES (1,1);
INSERT INTO USER_ROLES VALUES (2,2);
INSERT INTO USER_ROLES VALUES (3,3);
INSERT INTO USER_ROLES VALUES (4,4);

INSERT INTO ROLES VALUES (1,1,'Manager');
INSERT INTO ROLES VALUES (2,1,'Waiter');
INSERT INTO ROLES VALUES (3,1,'Cook');
INSERT INTO ROLES VALUES (4,1,'Barkeeper');

INSERT INTO ROLE_PERMISSIONS VALUES (
	1,
	1
);

INSERT INTO PERMISSIONS VALUES (
	1,
	1,
	'DISABLE'
);

INSERT INTO PRODUCTTYPES VALUES (1,1,'food');
INSERT INTO PRODUCTTYPES VALUES (2,1,'drink');

INSERT INTO PRODUCTS VALUES (1,1,'0.33l',TRUE,2.50,'Cola',1);
INSERT INTO PRODUCTS VALUES (2,1,'0.33l',TRUE,2.50,'Fanta',1);
INSERT INTO PRODUCTS VALUES (3,1,'0.33l',TRUE,2.50,'Spezi',1);
INSERT INTO PRODUCTS VALUES (4,1,'0.33l',TRUE,2.50,'Apfelschorle',1);
INSERT INTO PRODUCTS VALUES (5,1,'0.33l',TRUE,2.50,'Bier',1);
INSERT INTO PRODUCTS VALUES (6,1,'0.33l',TRUE,2.50,'Weizen',1);



INSERT INTO TABLESCUSTOMER VALUES(1,1,1);
INSERT INTO TABLESCUSTOMER VALUES(2,1,2);





